image: Visual Studio 2017

shallow_clone: true

branches:
  only:
  - master

skip_branch_with_pr: true

skip_tags: true

skip_commits:
  files:
  - BUILDING.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENCE
  - README.md

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\build.ps1 -target appveyor -buildAssemblyVersion ($env:BuildVersion + $env:APPVEYOR_BUILD_NUMBER) -buildSemanticVersion ($env:BuildSemanticVersion + $env:APPVEYOR_BUILD_NUMBER)
  
test: off

deploy: off

artifacts:
- path: artifacts/build
- path: artifacts/packages
- path: artifacts/test